Write-Host "1. Start MySQL and create database:"
Write-Host "   mysql -u root -p < database/schema.sql"
Write-Host "   mysql -u root -p < database/seed.sql"
Write-Host "2. Import Amazon dataset:"
Write-Host "   cd python_service; python -m venv .venv; .\.venv\Scripts\activate; pip install -r requirements.txt; python import_amazon_sales.py"
Write-Host "3. Start Python analytics service:"
Write-Host "   uvicorn app:app --reload --port 8000"
Write-Host "4. Start backend:"
Write-Host "   cd backend; npm install; npm run dev"
Write-Host "5. Open frontend/index.html or deploy frontend folder to Vercel."
